spring:
  application:
    name: sireleve

# generate new keys, set PRIVATE_KEY and PUBLIC_KEY environment variables and use them for production 
jwt:
  private:
    key: classpath:app.dev.key
  public:
    key: classpath:app.dev.pub